server:
  port: 8082

authorization-server:
  uri: http://localhost:9001/authorization-server

resource-server:
  uri: http://localhost:9002/resource-server

spring:
  thymeleaf:
    mode: HTML

security:
  oauth2:
    client:
      client-id: bar-client-id
      client-secret: 3aefd491-61ae-4423-8e7b-bfd6fd4b15d4
      scope: resource.read, resource.write
      user-authorization-uri: ${authorization-server.uri}/oauth/authorize
      access-token-uri: ${authorization-server.uri}/oauth/token
    resource:
      user-info-uri: ${resource-server.uri}/user-info
