server:
  port: 9001
  context-path: /authorization-server

spring:
  thymeleaf:
    mode: HTML

#security:
#  oauth2:
#    authorization:
#      check-token-access: isAuthenticated()
#    client:
#      client-id: foo-client-id
#      client-secret: 535ee78a-cc58-49aa-82f6-d976a79456ce
#      scope: resource.read, resource.write
#      authorized-grant-types: authorization_code
#      auto-approve-scopes: resource.read, resource.write

doma:
  naming: snake_upper_case
